{% set name = "pydoc-markdown" %}
{% set version = "4.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydoc-markdown-{{ version }}.tar.gz
  sha256: 131636ed32324d255816e476d72eb592542f120fce0d9a4ddca888934bc51282

build:
  number: 1
  noarch: python
  entry_points:
    - pydoc-markdown = pydoc_markdown.main:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - click >=7.0.0,<8.0.0
    - databind.core >=1.0.0,<2.0.0
    - databind.json >=1.0.0,<2.0.0
    - docspec >=1.0.0,<2.0.0
    - docspec-python >=1.0.0,<2.0.0
    - docstring_parser >=0.11,<1.0
    - nr.fs >=1.6.0,<2.0.0
    - nr.pylang.utils >=0.1.1,<1.0.0
    - nr.stream >=0.1.2,<1.0.0
    - python >={{ python_min }},<4.0
    - pyyaml >=5.3.0,<6.0.0
    - requests >=2.23.0,<3.0.0
    - six >=1.11.0,<2.0.0
    - toml >=0.10.1,<1.0.0
    - watchdog

test:
  imports:
    - pydoc_markdown
    - pydoc_markdown.contrib
  commands:
    - pip check
    - pydoc-markdown --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/NiklasRosenstein/pydoc-markdown
  summary: Create Python API documentation in Markdown format.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - NiklasRosenstein
